site_name: gwc_datalib

theme: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false 
          heading_level: 2
          docstring_style: "numpy"